# https://sanderknape.com/2019/02/automated-deployments-kubernetes-gitlab/
image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

before_script:
  - export REGISTRY_HOST="clyde.local:5005"
  - export CONTAINER_IMAGE="${REGISTRY_HOST}/${CI_PROJECT_PATH}/master"
  - export CONTAINER_IMAGE_SHA="${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  - export KUBE_SERVER="https://10.133.33.49:6443"

build:
  stage: build
  script:
    - docker login -u nobody -p nobody ${REGISTRY_HOST}
    - docker build -t ${CONTAINER_IMAGE_SHA} .
    - docker tag ${CONTAINER_IMAGE_SHA} ${CONTAINER_IMAGE}:latest
    - docker push ${CONTAINER_IMAGE_SHA}
    - docker push ${CONTAINER_IMAGE}:latest

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${KUBE_SERVER}" --certificate-authority=${CERTIFICATE_AUTHORITY_DATA} --embed-certs=true
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
