apiVersion: apps/v1
kind: Deployment
metadata:
  name: import
  namespace: gitlab-managed-apps
  labels:
    app: import
spec:
  replicas: 3
  selector:
    matchLabels:
      app: import
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: import
    spec:
      containers:
        - name: import
          image: clyde.local:5005/taliesin/micro-import/master:prod
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/snippets/"
              name: file-server
          env:
            - name: MICRO_ENVIRONMENT
              value: "production"
            - name: DATABASE_API_URL
              value: "http://database-api.gitlab-managed-apps.svc.cluster.local:8080"
            - name: CONVERSION_API_URL
              value: "http://conversion-dev-api.gitlab-managed-apps.svc.cluster.local:8080"
      volumes:
        - name: file-server
          persistentVolumeClaim:
            claimName: file-server-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-dev
  namespace: gitlab-managed-apps
  labels:
    app: import-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: import-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: import-dev
    spec:
      containers:
        - name: import-dev
          image: clyde.local:5005/taliesin/micro-import/master:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/snippets/"
              name: file-server-dev
          env:
            - name: MICRO_ENVIRONMENT
              value: "dev"
            - name: DATABASE_API_URL
              value: "http://database-dev-api.gitlab-managed-apps.svc.cluster.local:8080"
            - name: CONVERSION_API_URL
              value: "http://conversion-dev-api.gitlab-managed-apps.svc.cluster.local:8080"
      volumes:
        - name: file-server-dev
          persistentVolumeClaim:
            claimName: file-server-dev-claim
