apiVersion: v1
kind: Service
metadata:
  name: import-api
  namespace: gitlab-managed-apps
  labels:
    app: import
spec:
  selector:
    app: import
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: import-api-dev
  namespace: gitlab-managed-apps
  labels:
    app: import-dev
spec:
  selector:
    app: import-dev
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
